//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_order { get; set; }
        public Nullable<System.DateTime> Data_add { get; set; }
        public Nullable<System.DateTime> Data_end { get; set; }
        public int Gear_id { get; set; }
        public int Fault_type_id { get; set; }
        public string Problem_description { get; set; }
        public int ID_User { get; set; }
        public Nullable<int> Status_id { get; set; }
        public Nullable<int> Executive_id { get; set; }
        public string Executive_comment { get; set; }
    
        public virtual Fault_type Fault_type { get; set; }
        public virtual Gear Gear { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
